### ISSUE TITLE
Support passing GitHub OAuth token to Composer

### ISSUE THREAD

**Issue by clue** [azjezz/setup-hhvm#3]
I'm frequently running into GitHub's rate limit when running my actions multiple times. This can be avoided by passing the  `GITHUB_TOKEN` secret to Composer. It's not too hard to add this manual common to my own workflow, but I wonder if it makes sense to support this as part of this action similar to this one:

```yaml
- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: '7.4'
  env:
    COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Or explicitly:

```
composer -q global config github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}
```

See also https://github.com/shivammathur/setup-php/pull/212

What do you think?
